image: docker:stable
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t irhawks/dind-local .
    - docker login --username docker --password docker upload.docker.nexus.irhawks.com
    #- docker run my-docker-image /script/to/run/tests

